name: Deploy Frontend to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Build
        env:
          NEXT_PUBLIC_API_URL: https://ionianems1-backend-erdrase6hwexhndz.italynorth-01.azurewebsites.net
        run: npm run build

      - name: Deploy out folder to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPSIP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "out/*"
          target: "/var/www/ionianems.com/public"
          strip_components: 1
          rm: true

      - name: Fix permissions and reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPSIP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            chown -R www-data:www-data /var/www/ionianems.com/public
            nginx -t
            systemctl reload nginx
